import React, { useContext, useEffect, useState } from 'react'
import Head from "next/head";
import Link from 'next/link';
import { Store } from '../utils/Store';
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import { useSession } from 'next-auth/react';
import { Menu } from '@headlessui/react';
import { DropdownLink } from './DropdownLink';

export default function Layout({title, children}){

  const { status, data: session} = useSession();

  const { state} = useContext(Store);
  const {cart} = state;
  const [cartItemsCount, setcartItemsCount] = useState(0);
  useEffect(() => {
    setcartItemsCount(cart.cartItems.reduce((a,c) => a + c.quantity, 0))

  }, [cart.cartItems]);

  return (
    <>
      <Head>
        <title>{title ? title + "- clothar" : "clothar"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer position="bottom-center" limit={1} />
      <div className="flex min-h-screen flex-col justify-between">
        <header className="text-lg">
          <nav className="flex h-12 items-center shadow-md px-4 justify-between">
            <Link href="/" className="text-lg font-bold">
              Clothar
            </Link>
            <div>
              <Link href="/cart" className="p-2">
                Cart
                {cartItemsCount > 0 && (
                  <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                    {cartItemsCount}
                  </span>
                )}
              </Link>
              {status === "loading" ? (
                "loading"
              ) : session?.user ? (
                <Menu as="div" className="relative inline-block">
                  <Menu.Button className="text-blue-600">
                    {session.user.name}
                  </Menu.Button>
                  <Menu.Items className="absolute right-0 w-56 origin-top-right bg-white shadow-lg">
                    <Menu.Items className="">
                      <DropdownLink className="dropdown-link" href="/profile">
                        Profile
                      </DropdownLink>
                    </Menu.Items>
                  </Menu.Items>
                </Menu>
              ) : (
                <Link href="/login" className="p-2">
                  Login
                </Link>
              )}
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex justify-center items-center h-10 shadow-inner">
          <p>Copyright © 2022 Clothar</p>
        </footer>
      </div>
    </>
  );
}

